// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz9AVCHjRzD_5NZg-DvsbodHhl-f8_ELQ',
    appId: '1:284217718758:web:7ef5f883847132950e4827',
    messagingSenderId: '284217718758',
    projectId: 'cheating-app-1c2b9',
    authDomain: 'cheating-app-1c2b9.firebaseapp.com',
    storageBucket: 'cheating-app-1c2b9.appspot.com',
    measurementId: 'G-DE7XC2XHW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaiBFOumgL_uV9imMD10vmFqThdMiysyc',
    appId: '1:284217718758:android:010e1b798cb8bf480e4827',
    messagingSenderId: '284217718758',
    projectId: 'cheating-app-1c2b9',
    storageBucket: 'cheating-app-1c2b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8frXUKr3bOE8G65zqcKTy8g4vvBWnSyk',
    appId: '1:284217718758:ios:c3fd71d02b92f5230e4827',
    messagingSenderId: '284217718758',
    projectId: 'cheating-app-1c2b9',
    storageBucket: 'cheating-app-1c2b9.appspot.com',
    androidClientId: '284217718758-63ke3jo6e6npa43fbj17b5cm9ekdj9s8.apps.googleusercontent.com',
    iosClientId: '284217718758-uhpakhbqpkiv8i992dkn6lemh3n76782.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
